-- USED_GOODS_BOARD 중고 거래 게시판
-- USED_GOODS_USER  중고 거래 게시판 사용자

SELECT u.USER_ID, u.NICKNAME, SUM(b.PRICE) as TOTAL_PRICE
FROM USED_GOODS_BOARD b
JOIN USED_GOODS_USER u ON b.WRITER_ID = u.USER_ID
WHERE b.STATUS = 'DONE'
GROUP BY b.WRITER_ID HAVING TOTAL_PRICE >= 700000
ORDER BY TOTAL_PRICE;
