SELECT a.USER_ID, a.NICKNAME, b.TOTAL_SALES
FROM USED_GOODS_USER a,
(
    select WRITER_ID, SUM(PRICE) as TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    having SUM(PRICE) >= 700000
) b
where a.USER_ID = b.WRITER_ID
ORDER BY TOTAL_SALES ASC;
