SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, B.NAME
FROM ANIMAL_INS A
LEFT JOIN ANIMAL_OUTS B
    ON A.ANIMAL_ID = B.ANIMAL_ID
    # 중성화 X : Intact / 중성화 O : Spayed, Neutered
WHERE A.SEX_UPON_INTAKE LIKE 'Intact%' 
AND (B.SEX_UPON_OUTCOME LIKE 'Neutered%' OR B.SEX_UPON_OUTCOME LIKE 'Spayed%')
ORDER BY A.ANIMAL_ID
